export const READ_ALL_JOBS="READ_ALL_JOBS";
export const READ_ALL_JOBS_SUCCESS="READ_ALL_JOBS_SUCCESS";
export const READ_ALL_JOBS_FAILED="READ_ALL_JOBS_FAILED";

export const GET_JOB_DETAILS="GET_JOB_DETAILS";